selectors:
  - v-popover-wrap
  - channel-link
  - channel-items__right
  - center-search-container
  - search-input-wrap flex_between
  - bili-live-card is-rcmd
  - bili-video-card is-rcmd
  - video-info-container report-wrap-module report-scroll-module
  - up-info-container
  - up-info--left
  - up-info--right
  - default-btn old-charge-btn following-charge-btn
  - default-btn new-charge-btn charge-btn-loaded
  - default-btn follow-btn b-gz following
  - default-btn follow-btn b-gz not-follow
  - video-page-card-small
  - root-reply-container
  - sub-reply-container
  - '#h-name'
  - avatar-container
pages:
  - https://search.bilibili.com/all?keyword=UI%E8%87%AA%E5%8A%A8%E5%8C%96&from_source=webtop_search&spm_id_from=333.1007&search_source=5
  - https://search.bilibili.com/all?keyword=%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96&from_source=webtop_search&spm_id_from=333.1007&search_source=5
  - https://search.bilibili.com/all?keyword=WongJingGit&from_source=webtop_search&spm_id_from=333.1007&search_source=5
  - https://bilibili.com/anime/?spm_id_from=333.337.0.0
  - https://live.bilibili.com/?spm_id_from=666.4.0.0
  - https://live.bilibili.com/3158628?hotRank=0&session_id=54974d72c675af67235cc2cae765215e_53ABB365-F6D8-489A-B28F-712E8C387897&launch_id=1000229&live_from=71003
  - https://www.bilibili.com/video/BV15W4y197Tq/?spm_id_from=333.337.search-card.all.click&vd_source=5b3322d0857ec7c0db481caf249e5595
  - https://live.bilibili.com/5050?hotRank=0&session_id=61835fa5c9c8787c4bdc690ea365215e_73B66B4F-216F-4B43-9142-26E9014ED8C8&launch_id=1000238&live_from=71004
  - https://live.bilibili.com/p/eden/area-tags?parentAreaId=14&areaId=0&visit_id=6zvx0bcrxx40
  - https://live.bilibili.com/30640642?hotRank=0&session_id=61835fa5c9c8787c4bdc690ea365215e_09A25512-4F73-453C-BA08-C14919AB001A&launch_id=1000238&live_from=71004
  - https://live.bilibili.com/p/eden/area-tags?parentAreaId=3&areaId=35&visit_id=60qxprj6brk0
  - https://www.bilibili.com/v/kichiku/?spm_id_from=333.1007.0.0
  - https://www.bilibili.com/v/dance/?spm_id_from=333.1073.0.0
  - https://search.bilibili.com/all?keyword=%E4%B8%89%E5%85%AB%E5%A4%A7%E7%9B%96&search_source=1
  - https://www.bilibili.com/video/BV1aV4y1R78b/?spm_id_from=333.337.search-card.all.click&vd_source=5b3322d0857ec7c0db481caf249e5595
  - https://search.bilibili.com/all?keyword=%E5%90%B4%E4%BA%A6%E5%87%A1%E7%BB%8F%E7%BA%AA%E5%85%AC%E5%8F%B8%E8%A2%AB%E5%BC%BA%E6%89%A7&search_source=1